# === config_focus.yaml: Y-Net for image + coefficient prediction ===

paths:
  unfocused_train: "/home/houtlaw/iono-net/data/aug25/train_image_recon_jnp_unfocused.csv"
  focused_train:   "/home/houtlaw/iono-net/data/aug25/train_image_recon_jnp.csv"
  coeff_train:     "/home/houtlaw/iono-net/data/aug25/train_compl_ampls_20250707_155312.csv"         # NEW: 12 real values per row

  unfocused_val:   "/home/houtlaw/iono-net/data/aug25/test_image_recon_jnp_unfocused.csv"
  focused_val:     "/home/houtlaw/iono-net/data/aug25/test_image_recon_jnp.csv"
  coeff_val:       "/home/houtlaw/iono-net/data/aug25/test_compl_ampls_20250707_155324.csv"           # NEW: 12 real values per row
  scatterers:      "/home/houtlaw/iono-net/data/aug25/test_nuStruct_withSpeckle_20250707_155322.csv"
  x_range:         "/home/houtlaw/iono-net/data/aug25/x_range_image_recon_jnp.csv"
  kpsi:            "/home/houtlaw/iono-net/data/aug25/kPsi_20250707_155325.csv"
  setup:           "/home/houtlaw/iono-net/data/aug25/setup_20250707_155325.json"

model:
  base_channels: 12
  dropout_rate:  0.20
  depth:         9

loss:
  l4_weight:    0.0 # Image sparsity loss (negative L4)
  coef_weight:  1 #0.15    # Coefficient regression weight
  recon_accuracy_weight: 1

optimizer:
  lr: 0.00008
  weight_decay: 0.33

training:
  epochs: 10
  batch_size: 8
  num_workers: 8
  max_train_samples: null   # null = use all
  max_val_samples:   null
  early_stopping_patience: 15
  early_stopping_min_delta: 0.00001

params:
  F: 100
  dx: 0.25