seed: 0

paths:
  label_data_file_path: '/home/houtlaw/iono-net/data/aug25/train_compl_ampls_20250707_155312.csv'  # Path to label data file
  signal_data_file_path: '/home/houtlaw/iono-net/data/aug25/train_uscStruct_vals_20250707_155313.csv'

  test_label_file_path: '/home/houtlaw/iono-net/data/aug25/test_compl_ampls_20250707_155324.csv'
  test_data_file_path: '/home/houtlaw/iono-net/data/aug25/test_uscStruct_vals_20250707_155324.csv'

  x_range_file_path: '/home/houtlaw/iono-net/data/aug25/meta_X_20250707_155325.csv'
  setup_file_path: '/home/houtlaw/iono-net/data/aug25/setup_20250707_155325.json'
  kpsi_file_path: '/home/houtlaw/iono-net/data/aug25/kPsi_20250707_155325.csv'

model:
  architecture: [64,64,32,16]  # Model architecture
  activation: 'ReLU'  # Activation function (e.g., relu, tanh, sigmoid)
  dropout_rate: 0.2

training:
  batch_size: 512 # Batch size
  gradient_clip_value: 1 # Gradient clipping value
  l2_reg_weight: 0.01
  l4_weight: 10 # weight for l4 cost
  fourier_weight: 0
  fourier_d1_weight: 0
  fourier_d2_weight: 0

learning_rate:
  fixed: 0.005

optimizer:
  maxiter_adam: 120  # Maximum number of iterations for Adam optimizer
