seed: 0

gpu_id: 0  # GPU ID to use for training

paths:
  label_data_file_path: '/home/houtlaw/iono-net/data/baselines/10k_lownoise/train_compl_ampls_20250206_104902.csv'  # Path to label data file
  signal_data_file_path: '/home/houtlaw/iono-net/data/baselines/10k_lownoise/test_uscStruct_vals_20250206_104913.csv'

  test_label_file_path: '/home/houtlaw/iono-net/data/baselines/10k_lownoise/test_compl_ampls_20250206_104913.csv'
  test_data_file_path: '/home/houtlaw/iono-net/data/baselines/10k_lownoise/test_uscStruct_vals_20250206_104913.csv'

model:
  architecture: [60,60,60,60]  # Model architecture
  activation: tanh  # Activation function (e.g., relu, tanh, sigmoid)

training:
  batch_size: 64  # Batch size
  gradient_clip_value: 0.1 # Gradient clipping value
  l2_reg_weight: 0.0003

learning_rate:
  initial: 0.0003  # Initial learning rate
  gamma: 1.5  # Learning rate decay factor
  step: 200 # Step size for learning rate decay
  final: 0.00001  # Final learning rate

optimizer:
  maxiter_adam: 1000  # Maximum number of iterations for Adam optimizer
