seed: 0

paths:
  label_data_file_path: '/home/houtlaw/iono-net/data/baselines/10k_lownoise/train_compl_ampls_20250206_104902.csv'
  signal_data_file_path: '/home/houtlaw/iono-net/data/baselines/10k_lownoise/train_uscStruct_vals_20250206_104902.csv'

  test_label_file_path: '/home/houtlaw/iono-net/data/baselines/10k_lownoise/test_compl_ampls_20250206_104913.csv'
  test_data_file_path: '/home/houtlaw/iono-net/data/baselines/10k_lownoise/test_uscStruct_vals_20250206_104913.csv'

  x_range_file_path: '/home/houtlaw/iono-net/data/baselines/10k_lownoise/meta_X_20250206_104914.csv'
  setup_file_path: '/home/houtlaw/iono-net/data/baselines/10k_lownoise/setup_20250206_104914.json'
  kpsi_file_path: '/home/houtlaw/iono-net/data/baselines/10k_lownoise/kPsi_20250206_104914.csv'

model:
  type: configurable   # 'configurable' or 'unet'

  # If type == 'configurable':
  architecture: [256,256,256,256,256,256]
  activation: tanh  # relu, tanh, gelu

  # If type == 'unet':
  depth: 3
  base_features: 32
  kernel_size: 3

training:
  batch_size: 16
  gradient_clip_value: 4.221883110492239
  l2_reg_weight: 0.03
  fourier_weight: 0
  image_diff_weight: 1
learning_rate:
  fixed: 0.004829288776927212

optimizer:
  maxiter_adam: 300

