seed: 0

gpu_id: 0  # GPU ID to use for training

paths:
  label_data_file_path: '/home/houtlaw/iono-net/data/baselines/high_everything/train_compl_ampls_20250120_163928.csv'  # Path to label data file
  signal_data_file_path: '/home/houtlaw/iono-net/data/baselines/high_everything/train_uscStruct_vals_20250120_163928.csv'

model:
  architecture: [3000,1093, 832, 328, 963,250, 188, 514]  # Model architecture
  activation: tanh  # Activation function (e.g., relu, tanh, sigmoid)

training:
  batch_size: 64  # Batch size
  max_epochs: 50  # Maximum number of epochs

learning_rate:
  initial: 0.003  # Initial learning rate
  gamma: 0.95  # Learning rate decay factor
  step: 2000  # Step size for learning rate decay
  final: 0.00001  # Final learning rate

optimizer:
  maxiter_adam: 10000  # Maximum number of iterations for Adam optimizer
