seed: 0

paths:
  label_data_file_path: '/home/houtlaw/iono-net/data/aug25/train_compl_ampls_20250707_155312.csv'  # Path to label data file
  signal_data_file_path: '/home/houtlaw/iono-net/data/aug25/train_image_recon_jnp_unfocused.csv'

  test_label_file_path: '/home/houtlaw/iono-net/data/aug25/test_compl_ampls_20250707_155324.csv'
  test_data_file_path: '/home/houtlaw/iono-net/data/aug25/test_image_recon_jnp_unfocused.csv'

  x_range_file_path: '/home/houtlaw/iono-net/data/aug25/meta_X_20250707_155325.csv'
  setup_file_path: '/home/houtlaw/iono-net/data/aug25/setup_20250707_155325.json'
  kpsi_file_path: '/home/houtlaw/iono-net/data/aug25/kPsi_20250707_155325.csv'

model:
  architecture: [4096,4096,4096,4096,4096,4096,4096,4096,4096]  # Model architecture
  #architecture: [1024,1024,1024,1024,1024,1024,1024,1024,1024,1024,1024]
  activation: 'ReLU'  # Activation function (e.g., relu, tanh, sigmoid)
  dropout_rate: 0.5

training:
  batch_size: 64 # Batch size
  gradient_clip_value: 1 # Gradient clipping value
  l2_reg_weight: 0.07
  l4_weight: 5 # weight for l4 cost
  fourier_weight: 1
  fourier_d1_weight: 0.1
  fourier_d2_weight: 0.1

learning_rate:
  fixed: 0.000005

optimizer:
  maxiter_adam: 100  # Maximum number of iterations for Adam optimizer
