architecture:
- 855
- 1315
- 609
- 163
- 64
- 32
batch_size: 32
layer_0_size: 855
layer_1_size: 1315
layer_2_size: 609
layer_3_size: 163
learning_rate_gamma: 0.8981873046635566
learning_rate_initial: 0.0006398757934743532
minloss: !!python/object/apply:jax._src.array._reconstruct_array
- !!python/name:numpy.core.multiarray._reconstruct ''
- !!python/tuple
  - !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
- !!python/tuple
  - 1
  - !!python/tuple []
  - !!python/object/apply:numpy.dtype
    args:
    - f4
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - false
  - !!binary |
    hwWKPA==
- weak_type: false
num_layers: 4
