seed: 0

paths:
  label_data_file_path: '/home/houtlaw/iono-net/data/0.5iono/train_image_recon_jnp.csv'
  data_file_path: '/home/houtlaw/iono-net/data/0.5iono/train_image_recon_jnp_unfocused.csv'
  test_label_file_path: '/home/houtlaw/iono-net/data/0.5iono/test_image_recon_jnp.csv'
  test_data_file_path: '/home/houtlaw/iono-net/data/0.5iono/test_image_recon_jnp_unfocused.csv'
  x_range_file_path: '/home/houtlaw/iono-net/data/0.5iono/x_range_image_recon_jnp.csv'
  setup_file_path: '/home/houtlaw/iono-net/data/0.5iono/setup_20250625_123749.json'
  kpsi_file_path: '/home/houtlaw/iono-net/data/0.5iono/kPsi_20250625_123749.csv'
  scatterer_file_path: ''

model_config: {
  'down_channels': [32, 64, 128, 256, 512, 1024, 2048],
  'bottleneck_channels': 4096,
  'up_channels': [2048, 1024, 512, 256, 128, 64, 32]
}
# kernel was 5, is now 11

training:
  batch_size: 128
  gradient_clip_value: 4.0
  l2_reg_weight: 0.001
  l4_weight: 0.5
  amp_weight: 0.07

learning_rate:
  fixed: 0.0000124

optimizer:
  num_epochs: 500

bagging:
  n_models: 1