architecture:
- 1103
- 215
- 352
- 915
- 1179
- 649
- 64
- 32
batch_size: 32
layer_0_size: 1103
layer_1_size: 215
layer_2_size: 352
layer_3_size: 915
layer_4_size: 1179
layer_5_size: 649
learning_rate_gamma: 0.9004913069714414
learning_rate_initial: 0.0004763666413818918
minloss: !!python/object/apply:jax._src.array._reconstruct_array
- !!python/name:numpy.core.multiarray._reconstruct ''
- !!python/tuple
  - !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
- !!python/tuple
  - 1
  - !!python/tuple []
  - !!python/object/apply:numpy.dtype
    args:
    - f4
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - false
  - !!binary |
    qamePA==
- weak_type: false
num_layers: 6
